import {languages, message, translatedBody, translatedSign} from './locales.js';

const $ = selector => document.querySelector(selector);
const esc = value => String(value ?? '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
function stored(key, value) { try { if (value === undefined) return localStorage.getItem(key); if (value === null) localStorage.removeItem(key); else localStorage.setItem(key, value); } catch { /* Storage is optional. */ } return null; }
const localLanguage = stored('wealth-language');
const browserLanguage = navigator.language.startsWith('zh') ? 'zh-CN' : navigator.language.split('-')[0];
const state = {locale: languages[localLanguage] ? localLanguage : languages[browserLanguage] ? browserLanguage : 'en', session:null, profiles:[], profileId:null, view:'today', report:null, mapData:null, journal:[], reportDate:localDate(), loading:false, error:null, authMode:'signin', messages:[], agentBusy:false, entryOpen:false, editing:null, selectedLine:null, selectedPlace:null, compare:[], bodyFilters:new Set(), angleFilters:new Set(['AC','DC','MC','IC']), card:'sun',equation:null,equationInputs:null};
let map, lineLayer, marker, reportController, agentController, generation=0, authEpoch=0, authRequestBusy=false;
const accountToken = () => `${authEpoch}:${state.session?.user?.id||''}`;
const t = key => message(key, state.locale);
const fmt = (value, digits=2) => typeof value === 'number' && Number.isFinite(value) ? new Intl.NumberFormat(state.locale, {maximumFractionDigits:digits}).format(value) : String(value ?? t('noData'));
const bodyName = body => translatedBody(body, state.locale);
const currentProfile = () => state.profiles.find(profile => profile.id === state.profileId);
const bodyNames = ['Sun','Moon','Mercury','Venus','Mars','Jupiter','Saturn','Uranus','Neptune','Pluto'];
const colors = {Sun:'#b97924',Moon:'#607283',Mercury:'#51846f',Venus:'#b96d80',Mars:'#c2644b',Jupiter:'#ad8428',Saturn:'#817146',Uranus:'#318c95',Neptune:'#4779a7',Pluto:'#835ba0'};
const iconPaths = {today:'M3 10 12 3l9 7v10H3ZM9 20v-7h6v7',map:'m3 5 6-2 6 2 6-2v16l-6 2-6-2-6 2Zm6-2v16m6-14v16',cycles:'M20 12a8 8 0 1 1-2.3-5.7M20 4v5h-5M12 7v5l3 2',agent:'M4 4h16v13H9l-5 4Zm4 5h8m-8 4h5',journal:'M5 3h14v18H5Zm4 5h6m-6 4h6m-6 4h3',profiles:'M15.5 7a3.5 3.5 0 1 1-7 0 3.5 3.5 0 0 1 7 0ZM5 21v-3a7 7 0 0 1 14 0v3',arrow:'M4 12h16m-6-6 6 6-6 6',plus:'M12 5v14M5 12h14',close:'m6 6 12 12M6 18 18 6',logout:'M9 4H4v16h5m5-13 5 5-5 5m-6-5h11',check:'m5 12 4 4L19 6',spark:'m12 3 2.4 6.6L21 12l-6.6 2.4L12 21l-2.4-6.6L3 12l6.6-2.4Z',download:'M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5',edit:'m15 4 5 5-11 11-6 1 1-6Zm-1 1 5 5'};
function icon(name, extra='') { return `<svg class="icon ${extra}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${iconPaths[name] || iconPaths.spark}"/></svg>`; }
function localDate() { const date = new Date(); return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`; }
function dateLabel(value) { if (!value) return t('noData'); const date = new Date(value.length === 10 ? `${value}T12:00:00` : value); return Number.isNaN(date.valueOf()) ? esc(value) : new Intl.DateTimeFormat(state.locale, {dateStyle:'medium'}).format(date); }
function localeSelect() { return `<label class="language-control"><span class="sr-only">${t('language')}</span><span aria-hidden="true">◎</span><select id="language" aria-label="${t('language')}">${Object.entries(languages).map(([key,label])=>`<option value="${key}" ${key===state.locale?'selected':''}>${label}</option>`).join('')}</select></label>`; }
function button(label, action, className='button', more='') { return `<button type="button" class="${className}" data-action="${action}" ${more}>${label}</button>`; }
function formError(error) { return error ? `<div class="notice danger" role="alert">${esc(error)}</div>` : ''; }
function toast(text) { const el = $('#toast'); el.textContent=text; el.classList.add('visible'); clearTimeout(toast.timer); toast.timer=setTimeout(()=>el.classList.remove('visible'), 4500); }
async function api(path, {method='GET', body, signal}={}) {
  const owner=accountToken(), protectAccount=!path.startsWith('/api/auth/')&&path!=='/api/session';
  const stillOwned=()=>!protectAccount||accountToken()===owner;
  let response;
  try { response = await fetch(path, {method, credentials:'same-origin', headers:{Accept:'application/json', ...(body!==undefined?{'Content-Type':'application/json'}:{}), ...(method!=='GET'?{'X-Wealth-Request':'1'}:{})}, body:body!==undefined?JSON.stringify(body):undefined, signal, cache:'no-store'}); }
  catch(error) { if(error.name==='AbortError') throw error; throw new Error(t('network')); }
  if(!stillOwned())throw new DOMException('Stale account request','AbortError');
  if (!response.ok) {
    const payload = await response.json().catch(()=>({}));
    const detail = typeof payload.detail==='string'?payload.detail:typeof payload.error==='string'?payload.error:'';
    if(!stillOwned())throw new DOMException('Stale account request','AbortError');
    const key = /ambiguous|nonexistent|does not exist|clock change/i.test(detail) ? 'dstError' : /birth time|unknown time|precise.*time/i.test(detail) ? 'timeRequired' : response.status===401 ? (state.session?.user?'sessionExpired':'authenticationError') : response.status===409 ? 'conflictError' : response.status===422||response.status===400 ? 'validationError' : response.status===429 ? 'rateLimited' : response.status>=500 ? 'serverError' : 'requestFailed';
    if(response.status===401 && state.session?.user && !path.includes('/auth/') && accountToken()===owner) { clearPrivateState(); render(); }
    const error = new Error(t(key)); error.status=response.status; error.detail=detail; throw error;
  }
  if(response.status===204) return null;
  const result=await response.json();
  if(!stillOwned())throw new DOMException('Stale account request','AbortError');
  return result;
}
function clearPrivateState() { reportController?.abort(); agentController?.abort(); generation++;authEpoch++; if(state.session?.user) stored(`wealth-profile-${state.session.user.id}`,null); Object.assign(state,{session:{user:null},profiles:[],profileId:null,report:null,mapData:null,journal:[],messages:[],error:null,selectedPlace:null,selectedLine:null,compare:[],loading:false,agentBusy:false,editing:null,followup:null,entryOpen:false,equation:null,equationInputs:null,view:'today',reportDate:localDate(),card:'sun',authMode:'signin'}); }
function render() {
  if(map) { map.remove(); map=null; lineLayer=null; marker=null; }
  document.documentElement.lang=state.locale;
  document.title=`Wealth Command Center${state.session?.user?' · '+t(state.view):''}`;
  $('.skip-link').textContent=t('skip');
  $('#app').innerHTML=state.session?.user ? shell() : authView();
  bindCommon();
  if(state.session?.user) bindApp(); else bindAuth();
  if(state.view==='map' && state.session?.user && state.mapData) initMap();
}
function authView() {
  return `<main id="main" class="auth-page"><section class="auth-story"><a class="brand" href="/" aria-label="Wealth Command Center"><span class="brand-mark">W</span><span>WEALTH<br><small>COMMAND CENTER</small></span></a><div class="auth-copy"><span class="eyebrow">${t('explore')}</span><h1>${t('tagline')}</h1><p>${t('intro')}</p><div class="orbital" aria-hidden="true"><div class="orbit one"></div><div class="orbit two"></div><div class="orbit three"></div><span class="orbit-core">W</span><i></i><b></b></div><div class="trust-row"><span>${icon('profiles')}${t('private')}</span><span>${icon('spark')}${t('grounded')}</span><span>◎ ${t('sixLanguages')}</span></div></div></section><section class="auth-form-wrap">${localeSelect()}<div class="auth-form"><span class="eyebrow">WEALTH COMMAND CENTER</span><h2>${t('welcome')}</h2><div class="segmented" role="group" aria-label="${t('account')}">${button(t('signin'),'auth-signin',state.authMode==='signin'?'active':'')}${button(t('register'),'auth-register',state.authMode==='register'?'active':'')}</div><form id="auth-form" novalidate><label>${t('email')}<input name="email" type="email" autocomplete="email" required maxlength="254" inputmode="email" placeholder="you@example.com"></label><label>${t('password')}<input name="password" type="password" autocomplete="${state.authMode==='register'?'new-password':'current-password'}" ${state.authMode==='register'?'minlength="12"':''} required maxlength="256" ${state.authMode==='register'?`aria-describedby="password-hint"`:''}></label>${state.authMode==='register'?`<p class="field-hint" id="password-hint">${t('passwordHint')}</p>`:''}<div id="auth-error">${formError(state.error)}</div><button class="button primary full" type="submit">${t(state.authMode)}${icon('arrow')}</button></form><p class="auth-note">${t('accountHint')}</p><div class="legal-note">${icon('spark')}<p>${t('notFinancial')}</p></div></div><span class="auth-footer">${t('privacy')}</span></section></main>`;
}
function shell() {
  const p=currentProfile();
  return `<div class="app-shell"><aside class="sidebar"><a class="brand" href="/" data-view="today"><span class="brand-mark">W</span><span>WEALTH<br><small>COMMAND CENTER</small></span></a><div class="workspace-label">${t('explore')}</div><nav aria-label="${t('menu')}">${['today','map','cycles','agent','journal','profiles'].map(view=>`<button class="nav-item ${state.view===view?'active':''}" data-view="${view}" aria-label="${t(view)}" ${state.view===view?'aria-current="page"':''}>${icon(view)}<span>${t(view)}</span>${state.view===view?'<i></i>':''}</button>`).join('')}</nav><div class="sidebar-bottom"><div class="framework-chip"><span></span>${t('symbolic')}</div><p>${t('notFinancial')}</p><button class="signout" data-action="logout">${icon('logout')}${t('logout')}</button></div></aside><div class="app-content"><header class="topbar"><div class="mobile-brand"><span class="brand-mark">W</span></div><div class="breadcrumb">Wealth Command Center <span>/</span> <strong>${t(state.view)}</strong></div><div class="topbar-actions">${localeSelect()}<span class="avatar" title="${esc(state.session.user.email)}">${esc(state.session.user.email?.charAt(0)?.toUpperCase()||'W')}</span></div></header><main id="main" class="main-content"><div class="profile-strip"><span class="profile-context">${icon('profiles')}<label class="sr-only" for="profile-switch">${t('chooseProfile')}</label><select id="profile-switch" ${!state.profiles.length?'disabled':''}>${state.profiles.length?state.profiles.map(p=>`<option value="${esc(p.id)}" ${p.id===state.profileId?'selected':''}>${esc(p.name)}</option>`).join(''):`<option>${t('chooseProfile')}</option>`}</select></span>${p?`<span class="profile-meta">${esc(p.place_name||p.timezone)}<span class="dot">·</span>${dateLabel(p.birth_date)}</span>`:''}${button(icon('plus')+t('addProfile'),'new-profile','button subtle small')}</div>${pageView()}<footer class="page-footer"><span>Wealth Command Center <span class="version">${esc(state.session.version||'')}</span></span><span>${t('symbolic')} · ${t('privacy')}</span></footer></main><nav class="mobile-nav" aria-label="${t('menu')}">${['today','map','cycles','agent','journal','profiles'].map(view=>`<button data-view="${view}" ${state.view===view?'aria-current="page"':''}>${icon(view)}<span>${t(view)}</span></button>`).join('')}</nav></div></div>`;
}
function heading(title,subtitle,eyebrow=t(state.view)) { return `<div class="page-heading"><div><span class="eyebrow">${eyebrow}</span><h1>${title}</h1><p>${subtitle}</p></div></div>`; }
function noProfile() { return `<section class="empty-state card"><div class="empty-icon">${icon('profiles')}</div><h2>${t('noProfiles')}</h2><p>${t('noProfilesBody')}</p>${button(icon('plus')+t('addProfile'),'new-profile','button primary')}</section>`; }
function loadError() { if(state.loading)return `<div class="loading-state" role="status"><span class="spinner"></span>${t('load')}</div>`; if(state.error)return `<div class="notice danger"><h2>${t('error')}</h2><p>${esc(state.error)}</p>${button(t('retry'),'retry','button secondary')}${button(t('goProfiles'),'edit-current','button subtle')}</div>`; return ''; }
function pageView() {
  if(state.view==='profiles') return profilesView();
  if(!currentProfile())return noProfile();
  if(state.view==='today')return todayView();
  if(state.view==='cycles')return cyclesView();
  if(state.view==='map')return mapView();
  if(state.view==='agent')return agentView();
  return journalView();
}
function reportControls() { return `<form id="report-date" class="date-control"><label for="reference-date">${t('date')}</label><input id="reference-date" type="date" name="date" value="${state.reportDate}" required><button class="button secondary small" type="submit">${t('refresh')}</button></form>`; }
function todayView() {
  const r=state.report, score=r?.score?.value;
  return `${heading(t('overviewHeading'),t('overviewBody'),t('explore'))}${reportControls()}${loadError()}${!r?'':`<div class="overview-grid"><section class="score-card"><div class="score-card-top"><span class="pill">${icon('spark')}${t('symbolic')}</span><span class="fine-print">${dateLabel(state.reportDate)}</span></div><div class="score-layout"><div><h2>${t('score')}</h2><strong class="score-value">${score==null?'—':fmt(score,1)}</strong><p>${t('scoreNote')}</p></div><div class="score-orbit" aria-hidden="true"><div></div><span>✧</span></div></div><div class="score-breakdown"><div><span>${t('aspect')}</span><strong>${fmt(r.score?.aspect)}</strong></div><div><span>${t('dignity')}</span><strong>${fmt(r.score?.dignity)}</strong></div><div><span>${t('raw')}</span><strong>${fmt(r.score?.raw)}</strong></div></div></section><section class="action-card card"><span class="eyebrow">${t('reflection')}</span><div class="action-glyph">${icon('journal')}</div><h2>${t('actionTitle')}</h2><p>${t('actionBody')}</p>${button(t('reflect')+icon('arrow'),'reflect','text-button')}</section></div>${warnings(r.warnings)}<div class="section-title"><div><span class="eyebrow">${t('calculation')}</span><h2>${t('chart')}</h2></div><span class="pill neutral">${t('ascendant')} ${fmt(r.chart?.ascendant)}°</span></div>${chartTable(r.chart)}<section class="card evidence-card"><div class="section-title"><div><h2>${t('evidence')}</h2><p>${t('evidenceHint')}</p></div>${button(icon('download')+t('exportData'),'export-report','button secondary small')}</div>${evidenceList(r.evidence)}<details class="provenance"><summary>${t('source')}</summary>${dataTree(r.provenance)}</details></section>${cosmicCard()}<div class="disclaimer">${icon('spark')}<p>${t('notFinancial')}</p></div>`}`;
}
function warnings(items) { return Array.isArray(items)&&items.length?`<details class="notice warning"><summary>${t('warnings')} <span class="count">${fmt(items.length,0)}</span></summary><ul>${items.map(item=>`<li>${esc(typeof item==='string'?item:JSON.stringify(item))}</li>`).join('')}</ul></details>`:''; }
function chartTable(chart) { const data=Array.isArray(chart?.bodies)?chart.bodies:Object.entries(chart?.bodies||{}).map(([name,value])=>typeof value==='object'?{name,...value}:{name,longitude:value}); return `<section class="card table-card"><div class="table-scroll" tabindex="0" role="region" aria-label="${t('chart')}"><table><thead><tr><th>${t('body')}</th><th>${t('position')}</th><th>${t('sign')}</th><th>${t('house')}</th><th>${t('details')}</th></tr></thead><tbody>${data.map(item=>`<tr><th scope="row"><span class="planet-dot" style="background:${colors[item.name]||'#657c7b'}"></span>${esc(bodyName(item.name))}</th><td>${fmt(item.longitude??item.lon,4)}°</td><td>${esc(translatedSign(item.sign,state.locale)||'—')}</td><td>${esc(item.house??'—')}</td><td><span class="motion ${item.retrograde?'retro':''}">${t(item.retrograde?'retrograde':'direct')}</span></td></tr>`).join('')}</tbody></table></div></section>`; }
function evidenceRow(item) { return `<article class="evidence-row"><div><code>${esc(item.id||'')}</code><h3>${esc(item.label||item.id||'')}</h3></div><div class="evidence-value">${typeof item.value==='object'?`<details class="compact-evidence"><summary>${t('details')}</summary>${dataTree(item.value,1)}</details>`:esc(fmt(item.value))}<span class="tag">${t(({calculated:'calculation',computed:'calculation',deterministic:'calculation',interpretive:'interpretation'})[item.kind]||item.kind||'calculation')}</span></div></article>`; }
function evidenceList(items) { if(!Array.isArray(items)||!items.length)return `<p class="muted">${t('evidenceUnavailable')}</p>`;return `<div class="evidence-list">${items.slice(0,5).map(evidenceRow).join('')}${items.length>5?`<details class="more-evidence"><summary>${t('details')} · +${fmt(items.length-5,0)}</summary>${items.slice(5).map(evidenceRow).join('')}</details>`:''}</div>`; }
function fieldLabel(key) { const aliases={wealth_score:'score',aspect_score:'aspect',dignity_score:'dignity',julian_day:'Julian Day',birth_date:'birthDate',birth_time:'birthTime',birth_utc:'UTC',timezone:'timezone',latitude:'latitude',longitude:'longitude',numerology:'numerology',typology:'typology',gates:'gates',calendar:'calendar',mayan:'mayan',cardology:'cardology',tarot:'tarot',name:'name',body:'body',sign:'sign',house:'house',retrograde:'retrograde'}; return t(aliases[key]||key); }
function dataTree(data,depth=0) {
  if(data==null)return `<span class="muted">${t('noData')}</span>`;
  if(typeof data==='boolean')return t(data?'yes':'no');
  if(typeof data!=='object')return esc(typeof data==='number'?fmt(data,6):data);
  if(depth>=3)return `<details class="raw-fields"><summary>${t('sourceFields')}</summary><pre>${esc(JSON.stringify(data,null,2))}</pre></details>`;
  const entries=Array.isArray(data)?data.map((value,index)=>[String(index+1),value]):Object.entries(data);
  if(!entries.length)return `<span class="muted">${t('noData')}</span>`;
  return `<dl class="data-tree depth-${depth}">${entries.slice(0,60).map(([key,value])=>`<div><dt>${esc(fieldLabel(key))}</dt><dd>${dataTree(value,depth+1)}</dd></div>`).join('')}</dl>`;
}
function cosmicCard() { const labels={en:['Cosmic cards','A shareable symbolic card from your existing chart.','Download SVG'],ja:['コズミックカード','既存の出生図から作る、共有可能な象徴カード。','SVGを保存'],'zh-CN':['宇宙卡片','由现有星盘生成、可分享的象征卡片。','下载SVG'],th:['การ์ดจักรวาล','การ์ดเชิงสัญลักษณ์ที่แบ่งปันได้จากดวงเดิมของคุณ','ดาวน์โหลด SVG'],ko:['코스믹 카드','기존 차트로 만든 공유 가능한 상징 카드.','SVG 다운로드'],vi:['Thẻ vũ trụ','Thẻ biểu tượng có thể chia sẻ từ bản đồ sao hiện có.','Tải SVG']}; const l=labels[state.locale],url=`/api/profiles/${encodeURIComponent(state.profileId)}/cards/${state.card}`; return `<section class="card cosmic-card"><div><span class="eyebrow">${t('symbolic')}</span><h2>${l[0]}</h2><p>${l[1]}</p><label>${t('body')}<select id="card-body">${bodyNames.map(body=>`<option value="${body.toLowerCase()}" ${body.toLowerCase()===state.card?'selected':''}>${esc(bodyName(body))}</option>`).join('')}</select></label><a class="button secondary" href="${url}?format=svg&locale=${state.locale}" download="cosmic-card.svg">${icon('download')}${l[2]}</a><a class="text-button" href="${url}?locale=${state.locale}" target="_blank" rel="noopener">JSON ${icon('arrow')}</a></div><div class="cosmic-image"><img src="${url}?format=svg&locale=${state.locale}" alt="${esc(l[0]+' · '+bodyName(bodyNames.find(b=>b.toLowerCase()===state.card)))}" loading="lazy" id="cosmic-preview"><p class="muted" id="cosmic-error" hidden>${t('unavailable')}</p></div></section>`; }
function cyclesView() { return `${heading(t('cyclesTitle'),t('cyclesIntro'))}${reportControls()}${loadError()}${state.report?`${warnings(state.report.warnings)}<div class="system-grid">${['numerology','typology','gates','calendar','mayan','cardology','tarot'].map((key,index)=>`<section class="card system-card"><div class="system-heading"><span class="system-number">0${index+1}</span><span class="tag">${t('symbolic')}</span></div><h2>${t(key)}</h2>${state.report.systems?.[key]?`<details class="system-details"><summary>${t('details')}</summary>${dataTree(state.report.systems[key])}</details>`:`<p class="muted">${t('noSystem')}</p>`}</section>`).join('')}</div>`:''}`; }
function mapView() { return `${heading(t('mapTitle'),t('mapIntro'))}${placeSearch('map')}${loadError()}${state.mapData?`<section class="map-panel card"><div class="map-toolbar"><details class="map-filters" open><summary>${t('filters')}</summary><div class="filter-content"><div class="filter-buttons">${button(t('all'),'all-bodies','text-button')}${button(t('none'),'no-bodies','text-button')}</div><div class="body-filter-list">${[...new Set(state.mapData.features?.map(feature=>feature.properties?.body).filter(Boolean))].map(body=>`<label class="filter-chip"><input type="checkbox" data-body="${esc(body)}" ${state.bodyFilters.has(body)?'checked':''}><span class="planet-dot" style="background:${colors[body]||'#657c7b'}"></span>${esc(bodyName(body))}</label>`).join('')}</div><fieldset class="angle-filters"><legend>${t('angles')}</legend>${['MC','IC','AC','DC'].map(angle=>`<label><input type="checkbox" data-angle="${angle}" ${state.angleFilters.has(angle)?'checked':''}>${t(angle.toLowerCase())}</label>`).join('')}</fieldset></div></details></div><div id="world-map" class="world-map" aria-label="${t('map')}" tabindex="0"></div><div id="map-selection">${mapSelection()}</div></section><div class="map-lower"><section class="card"><h2>${t('savedLocations')}</h2><p>${t('compareHint')}</p>${savedPlaces()}</section><section class="card sky-card"><span class="sky-glyph">✧</span><h2>${t('sky')}</h2><p>${t('skyHint')}</p><label>${t('body')}<select id="sky-body">${bodyNames.map(body=>`<option value="${body}" ${body==='Jupiter'?'selected':''}>${esc(bodyName(body))}</option>`).join('')}</select></label>${button(icon('download')+t('downloadSky'),'download-sky','button secondary')}${state.session.integrations?.stellarium?button(t('openSky'),'open-sky','button primary'):''}<div id="sky-error"></div></section></div>`:''}`; }
function mapSelection() { const line=state.selectedLine,place=state.selectedPlace; return `<div class="map-selection"><div class="line-context"><span class="eyebrow">${line?t('selectedLine'):t('location')}</span><h3>${line?`${esc(bodyName(line.body))} <span>· ${esc(line.angle)}</span>`:t('selectMap')}</h3>${line?`<p>${t('lineContext')}</p>`:''}</div>${place?`<form id="save-location" class="place-form"><div class="coordinate-pair"><span>${t('latitude')} <strong>${fmt(place.latitude,4)}°</strong></span><span>${t('longitude')} <strong>${fmt(place.longitude,4)}°</strong></span></div><label class="sr-only" for="place-name">${t('locationName')}</label><input id="place-name" name="title" required maxlength="120" placeholder="${t('locationName')}"><button type="submit" class="button primary small">${icon('plus')}${t('saveLocation')}</button></form>`:''}</div>`; }
function locationEntries() { return state.journal.filter(entry=>entry.kind==='location'); }
function readPlace(entry) { try { const p=JSON.parse(entry.body); return typeof p.latitude==='number'&&typeof p.longitude==='number'?p:null; } catch { return null; } }
function savedPlaces() { const entries=locationEntries(); if(!entries.length)return `<div class="small-empty">${icon('map')}<p>${t('noLocations')}</p></div>`; const selected=entries.filter(e=>state.compare.includes(e.id)); return `<div class="place-list">${entries.map(entry=>{const p=readPlace(entry);return `<label class="place-item"><input type="checkbox" data-compare="${esc(entry.id)}" ${state.compare.includes(entry.id)?'checked':''}><span><strong>${esc(entry.title)}</strong><small>${p?`${fmt(p.latitude,3)}°, ${fmt(p.longitude,3)}°`:esc(entry.body)}</small></span></label>`;}).join('')}</div>${selected.length===2?`<div class="compare-grid">${selected.map(entry=>{const p=readPlace(entry);return `<article><h3>${esc(entry.title)}</h3>${p?`<p>${t('latitude')} ${fmt(p.latitude,4)}°<br>${t('longitude')} ${fmt(p.longitude,4)}°</p>`:''}<p>${esc(entry.outcome||t('noData'))}</p></article>`;}).join('')}</div>`:`<p class="field-hint">${t('chooseTwo')} · ${fmt(selected.length,0)}/2</p>`}`; }
async function initMap() {
  const container=$('#world-map'); if(!container)return;
  if(!window.L) { container.innerHTML=`<div class="small-empty"><p>${t('mapUnavailable')}</p><details><summary>${t('details')}</summary>${dataTree(state.mapData)}</details></div>`;return; }
  map=L.map(container,{worldCopyJump:true,minZoom:1,maxZoom:8,zoomControl:true,attributionControl:true,preferCanvas:true}).setView([18,10],2);
  map.attributionControl.addAttribution('Natural Earth');
  map.getContainer().setAttribute('aria-label',t('map'));
  const zoomIn=container.querySelector('.leaflet-control-zoom-in'),zoomOut=container.querySelector('.leaflet-control-zoom-out');
  if(zoomIn) { zoomIn.title='+'; zoomIn.setAttribute('aria-label','+'); } if(zoomOut) { zoomOut.title='−';zoomOut.setAttribute('aria-label','−'); }
  const thisMap=map;
  fetch('/assets/world-boundaries.json').then(response=>{if(!response.ok)throw new Error();return response.json();}).then(data=>{if(map!==thisMap)return;L.geoJSON(data,{style:{fillColor:'#dbe4dd',fillOpacity:1,color:'#b0c0b8',weight:.65},interactive:false}).addTo(map).bringToBack();}).catch(()=>{if(map===thisMap)toast(t('mapUnavailable'));});
  drawLines();
  map.on('click',event=>selectPlace(event.latlng));
  if(state.selectedPlace)marker=L.circleMarker([state.selectedPlace.latitude,state.selectedPlace.longitude],{radius:7,color:'#102c32',fillColor:'#e9c882',fillOpacity:1,weight:2}).addTo(map);
}
function drawLines() { if(!map)return;if(lineLayer)map.removeLayer(lineLayer); lineLayer=L.geoJSON(state.mapData,{filter:feature=>state.bodyFilters.has(feature.properties?.body)&&state.angleFilters.has(String(feature.properties?.angle||'').toUpperCase()),style:feature=>({color:colors[feature.properties.body]||'#718985',weight:2.4,opacity:.8,dashArray:['IC','DC'].includes(feature.properties.angle)?'5 4':null}),onEachFeature:(feature,layer)=>{layer.bindTooltip(`${esc(bodyName(feature.properties.body))} · ${esc(feature.properties.angle)}`,{sticky:true});layer.on('click',event=>{L.DomEvent.stopPropagation(event);state.selectedLine={body:feature.properties.body,angle:feature.properties.angle};selectPlace(event.latlng);});}}).addTo(map); }
function selectPlace(latlng) { const longitude=((latlng.lng+180)%360+360)%360-180; state.selectedPlace={latitude:Number(latlng.lat.toFixed(6)),longitude:Number(longitude.toFixed(6))};if(marker)map.removeLayer(marker);marker=L.circleMarker([state.selectedPlace.latitude,state.selectedPlace.longitude],{radius:7,color:'#102c32',fillColor:'#e9c882',fillOpacity:1,weight:2}).addTo(map);$('#map-selection').innerHTML=mapSelection();bindSaveLocation(); }
function agentView() { return `${heading(t('aiTitle'),t('aiIntro'))}<section class="card chat-card"><div class="chat-toolbar"><span class="guide-avatar">${icon('spark')}</span><div><strong>${t('guide')}</strong><small>${t(state.session.ai_enabled?'aiMode':'guideMode')}</small></div><span class="status-dot"></span></div>${!state.session.ai_enabled?`<div class="notice info">${t('guideNotice')}</div>`:''}<div class="chat-messages" id="chat-messages" aria-live="polite" aria-relevant="additions text">${state.messages.length?state.messages.map(chatBubble).join(''):`<div class="chat-welcome">${icon('spark')}<h2>${t('guide')}</h2><p>${t('aiIntro')}</p><button class="prompt-chip" data-action="suggest-question">${t('questionPlaceholder')}${icon('arrow')}</button></div>`}${state.agentBusy?`<div class="message assistant pending" role="status"><span class="spinner"></span>${t('thinking')}</div>`:''}</div><form id="agent-form" class="chat-composer"><label class="sr-only" for="agent-question">${t('question')}</label><div class="composer-field"><textarea id="agent-question" name="message" rows="2" required maxlength="4000" placeholder="${t('questionPlaceholder')}" ${state.agentBusy?'disabled':''}></textarea><button type="submit" class="button primary" ${state.agentBusy?'disabled':''} aria-label="${t('send')}">${icon('arrow')}</button></div>${state.session.ai_enabled?`<label class="consent"><input name="use_cloud_ai" type="checkbox"><span>${t('cloudConsent')}<small>${t('cloudConsentHint')}</small></span></label>`:''}${state.agentBusy?button(t('cancelRequest'),'cancel-agent','text-button'):''}<p class="field-hint">${t('notFinancial')}</p></form></section>`; }
function chatBubble(item) { return `<article class="message ${item.role==='user'?'user':'assistant'}"><span class="message-author">${t(item.role==='user'?'you':'guide')}</span><div class="message-text">${esc(item.text)}</div>${item.error?`<span class="tag error-tag">${t('error')}</span>`:''}${item.role!=='user'&&!item.error?`<p class="message-disclaimer">${t('responseDisclaimer')}</p>`:''}${item.evidence?.length?`<details><summary>${t('linkedEvidence')}</summary>${evidenceList(item.evidence)}</details>`:''}${item.tool_trace?.length?`<details><summary>${t('trace')}</summary>${dataTree(item.tool_trace)}</details>`:''}${warnings(item.warnings)}</article>`; }
function journalView() { const entries=state.journal;return `${heading(t('journalTitle'),t('journalIntro'))}${equationView()}<div class="section-title"><span class="pill neutral">${fmt(entries.length,0)} · ${t('journal')}</span>${button(icon('plus')+t('newEntry'),'new-entry','button primary')}</div>${loadError()}${state.entryOpen?journalForm():''}<div class="journal-grid">${entries.length?entries.map(entry=>`<article class="card journal-entry"><div class="entry-meta"><span class="tag">${t(entry.kind)}</span><time>${dateLabel(entry.created_at)}</time></div><h2>${esc(entry.title)}</h2>${journalBody(entry)}${entry.outcome?`<div class="outcome"><strong>${t('outcome')}</strong><p>${esc(entry.outcome)}</p></div>`:''}<div class="entry-actions">${button(t('updateOutcome'),'followup-entry','text-button',`data-id="${esc(entry.id)}"`)}${button(t('delete'),'delete-entry','text-button danger-text',`data-id="${esc(entry.id)}"`)}</div></article>`).join(''):`<div class="empty-state card"><div class="empty-icon">${icon('journal')}</div><h2>${t('emptyJournal')}</h2><p>${t('emptyJournalBody')}</p></div>`}</div>`; }
function journalForm() { return `<section class="card form-card"><div class="section-title"><h2>${t('newEntry')}</h2>${button(icon('close'),'close-entry','icon-button',`aria-label="${t('close')}"`)}</div><form id="journal-form" novalidate><div class="form-row"><label>${t('kind')}<select name="kind">${['reflection','decision','experiment'].map(kind=>`<option value="${kind}">${t(kind)}</option>`).join('')}</select></label><label>${t('title')}<input name="title" required maxlength="200" value="${esc(state.followup?.title||'')}"></label></div><label>${t('notes')}<textarea name="body" required maxlength="10000" rows="4">${esc(state.followup?.body||'')}</textarea></label><label>${t('outcome')} <span class="optional">${t('optional')}</span><textarea name="outcome" maxlength="5000" rows="2"></textarea></label><div id="journal-error"></div><button type="submit" class="button primary">${t('saveEntry')}${icon('check')}</button></form></section>`; }
function journalBody(entry) {
  if(entry.kind==='location'&&readPlace(entry)){const place=readPlace(entry);return `<p class="entry-body">${t('latitude')}: ${fmt(place.latitude,4)}°\n${t('longitude')}: ${fmt(place.longitude,4)}°</p>`;}
  if(entry.kind==='experiment'){try{const result=JSON.parse(entry.body);if(result.kind==='experimental'&&typeof result.formula==='string')return `<div class="equation-result"><code>${esc(result.formula)}</code><div><span>${t('raw')}<strong>${esc(fmt(result.raw,3))}</strong></span><span>${t('normalized')}<strong>${esc(fmt(result.normalized,3))}</strong></span></div><details><summary>${t('sourceFields')}</summary>${dataTree(result)}</details></div>`;}catch{/* Ordinary journal text is not structured experiment data. */}}
  return `<p class="entry-body">${esc(entry.body)}</p>`;
}
function profilesView() { return `${heading(t('profilesTitle'),t('profilesIntro'))}<div class="profiles-grid"><section><div class="profile-cards">${state.profiles.map(p=>`<article class="card profile-card"><div class="profile-card-top"><span class="profile-initial">${esc(p.name.slice(0,1))}</span><div><h2>${esc(p.name)}</h2><p>${esc(p.place_name||p.timezone)}</p></div>${p.id===state.profileId?`<span class="tag">${t('current')}</span>`:''}</div><dl><div><dt>${t('birthDate')}</dt><dd>${dateLabel(p.birth_date)}</dd></div><div><dt>${t('birthTime')}</dt><dd>${esc(p.birth_time||t('unknown'))}</dd></div><div><dt>${t('timezone')}</dt><dd>${esc(p.timezone)}</dd></div></dl><div class="profile-actions">${button(t('viewReport'),'select-profile','text-button',`data-id="${esc(p.id)}"`)}${button(icon('edit')+t('edit'),'edit-profile','text-button',`data-id="${esc(p.id)}"`)}${button(t('delete'),'delete-profile','text-button danger-text',`data-id="${esc(p.id)}"`)}</div></article>`).join('')}</div><section class="card account-card"><h2>${t('account')}</h2><p>${esc(state.session.user.email)}</p><p class="muted">${t('privacy')}</p><a href="/api/export" class="button secondary" download="wealth-account.json">${icon('download')}${t('exportAccount')}</a>${button(icon('logout')+t('logout'),'logout','text-button danger-text')}</section></section>${profileForm()}</div>`; }
function profileForm() { const p=state.editing||{},val=key=>esc(p[key]??'');return `<section class="card form-card" id="profile-form-card"><div class="section-title"><h2>${t(state.editing?'edit':'addProfile')}</h2>${state.editing?button(t('cancel'),'new-profile','text-button'):''}</div><form id="profile-form" novalidate><label>${t('name')}<input name="name" required maxlength="100" autocomplete="off" value="${val('name')}"></label>${placeSearch('profile')}<label>${t('locationName')}<input name="place_name" maxlength="200" autocomplete="off" value="${val('place_name')}"></label><div class="form-row"><label>${t('birthDate')}<input type="date" name="birth_date" required max="${localDate()}" value="${val('birth_date')}"></label><label>${t('birthTime')}<input type="time" name="birth_time" step="1" value="${val('birth_time')}" ${p.birth_time===null?'disabled':''}></label></div><label class="checkbox-line"><input name="unknown_time" type="checkbox" ${p.birth_time===null?'checked':''}>${t('unknown')}</label><div id="unknown-warning" class="notice warning" ${p.birth_time===null?'':'hidden'}>${t('timeUnknown')}</div><label>${t('timezone')}<input name="timezone" required list="timezones" placeholder="Asia/Tokyo" value="${val('timezone')}"></label><datalist id="timezones">${['UTC','Asia/Tokyo','Asia/Shanghai','Asia/Bangkok','Asia/Seoul','Asia/Ho_Chi_Minh','Asia/Taipei','Asia/Singapore','Europe/London','Europe/Paris','America/New_York','America/Los_Angeles','America/Sao_Paulo','Australia/Sydney','Africa/Johannesburg'].map(zone=>`<option value="${zone}">`).join('')}</datalist><p class="field-hint">${t('timezoneHint')}</p><div class="form-row"><label>${t('latitude')}<input name="latitude" type="number" step="any" min="-90" max="90" required value="${val('latitude')}"></label><label>${t('longitude')}<input name="longitude" type="number" step="any" min="-180" max="180" required value="${val('longitude')}"></label></div><p class="field-hint">${t('coordinatesHint')}</p><details class="advanced"><summary>${t('advanced')}</summary><div class="form-row"><label>${t('enneagram')}<select name="enneagram_type"><option value="">—</option>${Array.from({length:9},(_,i)=>`<option value="${i+1}" ${String(p.enneagram_type)===String(i+1)?'selected':''}>${fmt(i+1,0)}</option>`).join('')}</select></label><label>${t('mbti')}<select name="mbti_type"><option value="">—</option>${['INTJ','INTP','ENTJ','ENTP','INFJ','INFP','ENFJ','ENFP','ISTJ','ISFJ','ESTJ','ESFJ','ISTP','ISFP','ESTP','ESFP'].map(type=>`<option ${p.mbti_type===type?'selected':''}>${type}</option>`).join('')}</select></label></div><label>${t('numerologyName')}<input name="numerology_name" maxlength="200" value="${val('numerology_name')}"></label></details><div id="profile-error"></div><button type="submit" class="button primary full">${t(state.editing?'updateProfile':'saveProfile')}${icon('arrow')}</button></form></section>`; }
function bindCommon() { $('#language')?.addEventListener('change',event=>{const drafts=[...document.querySelectorAll('form[id]')].map(form=>[form.id,[...form.elements].filter(field=>field.name&&field.tagName!=='BUTTON').map(field=>({name:field.name,value:field.value,checked:field.checked,disabled:field.disabled}))]);state.locale=event.target.value;stored('wealth-language',state.locale);render();for(const [id,fields] of drafts){const form=document.getElementById(id);if(!form)continue;for(const saved of fields){const field=form.elements[saved.name];if(field){field.value=saved.value;field.checked=saved.checked;field.disabled=saved.disabled;}}}const unknown=$('#profile-form [name="unknown_time"]');if(unknown&&$('#unknown-warning'))$('#unknown-warning').hidden=!unknown.checked;});document.querySelectorAll('[data-view]').forEach(el=>el.addEventListener('click',event=>{event.preventDefault();navigate(el.dataset.view);}));document.querySelectorAll('[data-action]').forEach(el=>el.addEventListener('click',()=>action(el.dataset.action,el))); }
function bindAuth() { $('#auth-form')?.addEventListener('submit',async event=>{event.preventDefault();if(authRequestBusy)return;const form=event.currentTarget,data=Object.fromEntries(new FormData(form));if(!form.checkValidity()){showFormError('auth-error',t('required'));return;}if(state.authMode==='register'&&data.password.length<12){showFormError('auth-error',t('passwordInvalid'));return;}authRequestBusy=true;setBusy(form,true);try {await api(`/api/auth/${state.authMode==='register'?'register':'login'}`,{method:'POST',body:data});const session=await api('/api/session');authEpoch++;state.session=session;state.error=null;await loadProfiles();render();await loadView();}catch(error){if(error.name!=='AbortError')showFormError('auth-error',error.message);}finally{authRequestBusy=false;setBusy(form,false);} }); }
function bindApp() {
  bindPlaceSearch();
  $('#equation-form')?.addEventListener('submit',submitEquation);
  $('#profile-switch')?.addEventListener('change',event=>selectProfile(event.target.value));
  $('#report-date')?.addEventListener('submit',event=>{event.preventDefault();const date=new FormData(event.currentTarget).get('date');if(!/^\d{4}-\d{2}-\d{2}$/.test(date))return;state.reportDate=date;state.report=null;loadView();});
  $('#profile-form')?.addEventListener('submit',saveProfile);
  $('#profile-form [name="unknown_time"]')?.addEventListener('change',event=>{const field=$('#profile-form [name="birth_time"]');field.disabled=event.target.checked;$('#unknown-warning').hidden=!event.target.checked;});
  $('#journal-form')?.addEventListener('submit',saveJournal);
  $('#agent-form')?.addEventListener('submit',sendAgent);
  $('#agent-question')?.addEventListener('keydown',event=>{if(event.key==='Enter'&&(event.ctrlKey||event.metaKey)){event.preventDefault();$('#agent-form').requestSubmit();}});
  document.querySelectorAll('[data-body]').forEach(el=>el.addEventListener('change',()=>{if(el.checked)state.bodyFilters.add(el.dataset.body);else state.bodyFilters.delete(el.dataset.body);drawLines();}));
  document.querySelectorAll('[data-angle]').forEach(el=>el.addEventListener('change',()=>{if(el.checked)state.angleFilters.add(el.dataset.angle);else state.angleFilters.delete(el.dataset.angle);drawLines();}));
  document.querySelectorAll('[data-compare]').forEach(el=>el.addEventListener('change',()=>{if(el.checked){if(state.compare.length===2){el.checked=false;toast(t('chooseTwo'));return;}state.compare.push(el.dataset.compare);}else state.compare=state.compare.filter(id=>id!==el.dataset.compare);const center=map?.getCenter(),zoom=map?.getZoom();render();if(center&&map)map.setView(center,zoom);}));
  $('#card-body')?.addEventListener('change',event=>{state.card=event.target.value;const card=$('.cosmic-card');card.outerHTML=cosmicCard();bindCard();});
  $('#cosmic-preview')?.addEventListener('error',()=>{if($('#cosmic-preview'))$('#cosmic-preview').hidden=true;if($('#cosmic-error'))$('#cosmic-error').hidden=false;});
  bindSaveLocation();
}
function placeSearch(context) { return `<div class="place-search" data-context="${context}"><label for="place-query-${context}">${t(context==='profile'?'searchCity':'location')}</label><div class="place-search-field"><input id="place-query-${context}" ${context==='profile'?'name="place_query"':''} type="search" maxlength="100" autocomplete="off" placeholder="Tokyo · 東京 · กรุงเทพฯ" aria-describedby="place-hint-${context}"><button type="button" class="button secondary small" data-search-place="${context}">${t('search')}</button></div><div id="place-results-${context}" class="place-results" aria-live="polite"></div><p class="field-hint" id="place-hint-${context}">${t('cityHint')} <span>${t('citySource')}: <a href="https://www.geonames.org/" target="_blank" rel="noopener noreferrer">GeoNames</a></span></p></div>`; }
function bindPlaceSearch() { document.querySelectorAll('[data-search-place]').forEach(button=>{button.addEventListener('click',()=>searchPlaces(button.dataset.searchPlace));const field=$(`#place-query-${button.dataset.searchPlace}`);field?.addEventListener('keydown',event=>{if(event.key==='Enter'){event.preventDefault();searchPlaces(button.dataset.searchPlace);}});}); }
async function searchPlaces(context) {
  const input=$(`#place-query-${context}`),q=input?.value.trim(),results=$(`#place-results-${context}`),owner=accountToken();if(!q||!results)return;
  results.innerHTML=`<div class="field-hint">${t('load')}</div>`;
  try {const places=await api(`/api/places?q=${encodeURIComponent(q)}`);if(owner!==accountToken()||!document.contains(results)||input.value.trim()!==q)return;results.innerHTML=places.length?places.map((place,index)=>`<button class="place-result" type="button" data-place-index="${index}"><strong>${esc(place.name)}</strong><span>${esc(place.country||place.country_code||'')} · ${esc(place.timezone)}</span></button>`).join(''):`<p class="field-hint">${t('noPlaces')}</p>`;results.querySelectorAll('[data-place-index]').forEach(button=>button.addEventListener('click',()=>{const place=places[Number(button.dataset.placeIndex)];if(context==='profile'){const form=$('#profile-form');for(const field of ['latitude','longitude','timezone'])form.elements[field].value=place[field];form.elements.place_name.value=`${place.name}${place.country?', '+place.country:''}`;input.value=place.name;results.innerHTML=`<p class="field-hint">${icon('check')}${t('saved')} · ${esc(place.name)}</p>`;form.elements.latitude.focus();}else{state.selectedLine=null;if(map){map.setView([place.latitude,place.longitude],5);selectPlace({lat:place.latitude,lng:place.longitude});if($('#place-name'))$('#place-name').value=place.name;$('#save-location')?.scrollIntoView({behavior:'smooth',block:'nearest'});}else toast(t('mapUnavailable'));}}));}
  catch(error){if(owner===accountToken()&&document.contains(results)&&error.name!=='AbortError')results.innerHTML=formError(error.message);}
}
function equationView() {
  const fields=['capital','human','intellectual','social','execution','allocation','feedback','risk','timing','location'];
  return `<details class="card equation-panel" ${state.equation?'open':''}><summary><span>${t('equation')}</span><span class="tag">${t('experimental')}</span></summary><p>${t('equationIntro')}</p><form id="equation-form" novalidate><div class="equation-fields">${fields.map(key=>{const factor=['timing','location'].includes(key);return `<label>${t(key==='location'?'locationFactor':key)}<span class="input-range">${factor?'0–2':key==='feedback'?'−100–100':'0–100'}</span><input type="number" name="${key}" min="${key==='feedback'?-100:0}" max="${factor?2:100}" step="any" value="${esc(state.equationInputs?.[key]??(factor?1:0))}" required></label>`;}).join('')}</div><p class="field-hint">${t('equationDefaults')}</p><div class="equation-actions"><button type="submit" name="intent" value="calculate" class="button secondary">${t('calculate')}</button><button type="submit" name="intent" value="save" class="button primary">${t('saveExperiment')}</button></div><div id="equation-error"></div></form>${state.equation?`<div class="equation-result"><code>${esc(state.equation.formula)}</code><div><span>${t('raw')}<strong>${fmt(state.equation.raw,3)}</strong></span><span>${t('normalized')}<strong>${fmt(state.equation.normalized,3)}</strong></span></div><details><summary>${t('sourceFields')}</summary>${dataTree(state.equation.terms)}</details>${state.equation.journal_id?`<span class="tag">${t('saved')}</span>`:''}</div>`:''}</details>`;
}
async function submitEquation(event) {
  event.preventDefault();const form=event.currentTarget;if(!form.checkValidity())return showFormError('equation-error',t('validationError'));
  const owner=accountToken(),pid=state.profileId,inputs=Object.fromEntries([...new FormData(form)].map(([key,value])=>[key,Number(value)]));
  setBusy(form,true);try{const result=await api('/api/equation',{method:'POST',body:{...inputs,profile_id:pid,save:event.submitter?.value==='save'}});if(owner!==accountToken()||pid!==state.profileId)return;state.equation=result;state.equationInputs=inputs;if(result.journal_id)await loadView();else render();}catch(error){if(owner===accountToken()&&pid===state.profileId&&error.name!=='AbortError')showFormError('equation-error',error.message);}finally{setBusy(form,false);}
}
function bindCard(){ $('#card-body')?.addEventListener('change',event=>{state.card=event.target.value;$('.cosmic-card').outerHTML=cosmicCard();bindCard();});$('#cosmic-preview')?.addEventListener('error',()=>{$('#cosmic-preview').hidden=true;$('#cosmic-error').hidden=false;}); }
function showFormError(id,text) { const node=$('#'+id);if(node){node.innerHTML=formError(text);node.scrollIntoView({block:'nearest',behavior:'smooth'});}else toast(text); }
function setBusy(form,busy) { form.setAttribute('aria-busy',String(busy));form.querySelectorAll('button[type="submit"]').forEach(button=>{button.disabled=busy;if(busy){button.dataset.original=button.innerHTML;button.innerHTML=`<span class="spinner"></span>${t('saving')}`;}else if(button.dataset.original)button.innerHTML=button.dataset.original;}); }
async function loadProfiles() { const owner=accountToken(),result=await api('/api/profiles');if(owner!==accountToken()||!state.session?.user)return;state.profiles=Array.isArray(result)?result:result.profiles||[];const saved=stored(`wealth-profile-${state.session.user.id}`);if(!state.profiles.some(p=>p.id===state.profileId))state.profileId=state.profiles.find(p=>p.id===saved)?.id||state.profiles[0]?.id||null;if(!state.profiles.length)state.view='profiles'; }
async function selectProfile(id) { if(id===state.profileId&&state.report)return;reportController?.abort();agentController?.abort();generation++;Object.assign(state,{profileId:id,report:null,mapData:null,journal:[],messages:[],error:null,selectedPlace:null,selectedLine:null,compare:[],agentBusy:false,entryOpen:false,followup:null,equation:null,equationInputs:null});stored(`wealth-profile-${state.session.user.id}`,id);render();await loadView(); }
async function navigate(view) { if(!['today','map','cycles','agent','journal','profiles'].includes(view))return;state.view=view;state.error=null;render();window.scrollTo({top:0,behavior:'instant'});await loadView(); }
async function loadView() {
  if(!currentProfile()||state.view==='profiles'||state.view==='agent')return;
  reportController?.abort();reportController=new AbortController();const token=++generation,view=state.view,pid=state.profileId;
  const requests=[];
  if(['today','cycles'].includes(view)&&!state.report)requests.push(['report',`/api/profiles/${encodeURIComponent(pid)}/report?date=${state.reportDate}`]);
  if(view==='map'&&!state.mapData)requests.push(['mapData',`/api/profiles/${encodeURIComponent(pid)}/map`]);
  if(['journal','map'].includes(view))requests.push(['journal',`/api/journal?profile_id=${encodeURIComponent(pid)}`]);
  if(!requests.length)return;
  state.loading=true;state.error=null;render();
  const results=await Promise.allSettled(requests.map(async([key,path])=>[key,await api(path,{signal:reportController.signal})]));
  if(token!==generation||state.profileId!==pid||!state.session?.user)return;
  results.forEach((result,index)=>{if(result.status==='fulfilled'){const [key,data]=result.value;state[key]=data;if(key==='mapData')state.bodyFilters=new Set(data.features?.map(feature=>feature.properties?.body).filter(Boolean));if(key==='journal'&&!Array.isArray(data))state.journal=data.entries||[];}else if(result.reason.name!=='AbortError')state.error=result.reason.message;});
  state.loading=false;render();
}
async function saveProfile(event) {
  event.preventDefault();const form=event.currentTarget,fields=new FormData(form),body=Object.fromEntries(fields),owner=accountToken();
  if(!form.checkValidity())return showFormError('profile-error',t('required'));
  if(!body.birth_date||body.birth_date>localDate())return showFormError('profile-error',t('dateInvalid'));
  try{new Intl.DateTimeFormat('en',{timeZone:body.timezone}).format();}catch{return showFormError('profile-error',t('timezoneInvalid'));}
  body.latitude=Number(body.latitude);body.longitude=Number(body.longitude);
  if(!Number.isFinite(body.latitude)||!Number.isFinite(body.longitude)||Math.abs(body.latitude)>90||Math.abs(body.longitude)>180)return showFormError('profile-error',t('coordinatesInvalid'));
  body.birth_time=fields.has('unknown_time')?null:body.birth_time||null;delete body.unknown_time;delete body.place_query;['enneagram_type','mbti_type','numerology_name'].forEach(key=>body[key]=body[key]||null);
  const editing=state.editing;
  setBusy(form,true);try {const p=await api(editing?`/api/profiles/${encodeURIComponent(editing.id)}`:'/api/profiles',{method:editing?'PATCH':'POST',body});if(owner!==accountToken())return;state.editing=null;await loadProfiles();if(owner!==accountToken())return;state.profileId=null;state.view='today';await selectProfile(p.id);if(owner===accountToken())toast(t(editing?'edited':'profileCreated'));}catch(error){if(owner===accountToken()&&error.name!=='AbortError')showFormError('profile-error',error.message);}finally{setBusy(form,false);}
}
async function saveJournal(event) { event.preventDefault();const form=event.currentTarget;if(!form.checkValidity())return showFormError('journal-error',t('required'));const body={...Object.fromEntries(new FormData(form)),profile_id:state.profileId};setBusy(form,true);try{await api('/api/journal',{method:'POST',body});state.entryOpen=false;state.followup=null;await loadView();toast(t('saved'));}catch(error){showFormError('journal-error',error.message);}finally{setBusy(form,false);} }
function bindSaveLocation(){ $('#save-location')?.addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget;if(!form.checkValidity())return;const body={profile_id:state.profileId,kind:'location',title:new FormData(form).get('title'),body:JSON.stringify({...state.selectedPlace,line:state.selectedLine}),outcome:''};setBusy(form,true);try{await api('/api/journal',{method:'POST',body});await loadView();toast(t('saved'));}catch(error){toast(error.message);}finally{setBusy(form,false);} }); }
async function sendAgent(event) {
  event.preventDefault();const fields=new FormData(event.currentTarget),text=String(fields.get('message')||'').trim();if(!text||state.agentBusy)return;
  const pid=state.profileId;state.messages.push({role:'user',text});state.agentBusy=true;agentController=new AbortController();render();
  try {const response=await api('/api/agent',{method:'POST',body:{profile_id:pid,message:text,locale:state.locale,report_date:state.reportDate,use_cloud_ai:fields.has('use_cloud_ai')},signal:agentController.signal});if(state.profileId===pid&&state.session?.user)state.messages.push({role:'assistant',text:response.answer,evidence:response.evidence,tool_trace:response.tool_trace,warnings:response.warnings});}
  catch(error){if(state.profileId===pid&&state.session?.user)state.messages.push({role:'assistant',text:error.name==='AbortError'?t('cancelled'):error.message,error:true});}
  finally {if(state.profileId===pid&&state.session?.user){state.agentBusy=false;render();$('#chat-messages')?.scrollTo({top:$('#chat-messages').scrollHeight,behavior:'smooth'});$('#agent-question')?.focus();}}
}
async function action(name,el) {
  if(name==='auth-signin'||name==='auth-register'){state.authMode=name.slice(5);state.error=null;render();return;}
  if(name==='logout'){el.disabled=true;try{await api('/api/auth/logout',{method:'POST',body:{}});clearPrivateState();render();}catch(error){toast(error.message);el.disabled=false;}return;}
  if(name==='new-profile'){state.editing=null;state.view='profiles';render();$('#profile-form-card')?.scrollIntoView({behavior:'smooth',block:'start'});$('#profile-form [name="name"]')?.focus({preventScroll:true});return;}
  if(name==='edit-profile'||name==='edit-current'){state.editing=state.profiles.find(p=>p.id===(el.dataset.id||state.profileId));state.view='profiles';render();$('#profile-form-card')?.scrollIntoView({behavior:'smooth',block:'start'});return;}
  if(name==='select-profile'){state.view='today';await selectProfile(el.dataset.id);render();return;}
  if(name==='retry'){state.report=null;state.mapData=null;await loadView();return;}
  if(name==='reflect'){state.view='journal';state.entryOpen=true;state.followup=null;render();await loadView();return;}
  if(name==='new-entry'||name==='close-entry'){state.entryOpen=name==='new-entry';state.followup=null;render();return;}
  if(name==='followup-entry'){const entry=state.journal.find(e=>e.id===el.dataset.id);state.followup={title:entry.title,body:entry.kind==='location'?`${t('location')}: ${entry.title}`:entry.body};state.entryOpen=true;render();$('#journal-form [name="outcome"]')?.focus();return;}
  if(name==='delete-profile'){if(!confirm(t('deleteProfile')))return;const owner=accountToken();el.disabled=true;try{await api(`/api/profiles/${encodeURIComponent(el.dataset.id)}`,{method:'DELETE'});if(owner!==accountToken())return;const deletedCurrent=state.profileId===el.dataset.id;await loadProfiles();if(owner!==accountToken())return;if(deletedCurrent){state.report=null;state.mapData=null;state.journal=[];state.messages=[];state.selectedPlace=null;state.compare=[];state.followup=null;state.entryOpen=false;state.equation=null;state.equationInputs=null;}state.editing=null;render();toast(t('profileDeleted'));}catch(error){if(owner===accountToken()&&error.name!=='AbortError')toast(error.message);el.disabled=false;}return;}
  if(name==='delete-entry'){if(!confirm(t('deleteEntry')))return;el.disabled=true;try{await api(`/api/journal/${encodeURIComponent(el.dataset.id)}`,{method:'DELETE'});state.compare=state.compare.filter(id=>id!==el.dataset.id);await loadView();toast(t('saved'));}catch(error){toast(error.message);el.disabled=false;}return;}
  if(name==='all-bodies'||name==='no-bodies'){state.bodyFilters=name==='all-bodies'?new Set(state.mapData.features.map(feature=>feature.properties?.body)):new Set();document.querySelectorAll('[data-body]').forEach(input=>input.checked=state.bodyFilters.has(input.dataset.body));drawLines();return;}
  if(name==='suggest-question'){$('#agent-question').value=t('questionPlaceholder');$('#agent-question').focus();return;}
  if(name==='cancel-agent'){agentController?.abort();return;}
  if(name==='export-report'){const blob=new Blob([JSON.stringify(state.report,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='wealth-report.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);return;}
  if(name==='download-sky'){const body=$('#sky-body').value,a=document.createElement('a');a.href=`/api/profiles/${encodeURIComponent(state.profileId)}/stellarium-script?body=${encodeURIComponent(body)}`;a.download='wealth-sky.ssc';a.click();return;}
  if(name==='open-sky'){el.disabled=true;try{await api('/api/integrations/stellarium',{method:'POST',body:{profile_id:state.profileId,body:$('#sky-body').value}});toast(t('saved'));}catch(error){showFormError('sky-error',error.message);}finally{el.disabled=false;}}
}
async function boot(){try{state.session=await api('/api/session');if(state.session.user)await loadProfiles();render();await loadView();}catch(error){state.session={user:null};state.error=error.message;render();}if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});}
boot();
